### ISSUE TITLE
How to add global css file with classes ?

### ISSUE THREAD

**Issue by markopredovic** [rossmc/how-to-venia#3]
@rossmc , how to add global available css with classes also ? Currently only tag selectors in index.css are available globally.

**Comment by rossmc** [comment]
Hi @markopredovic,

With CSS modules the idea is you should avoid adding CSS this way, as it's `global scope CSS` rather than `component scope CSS`.

See:
https://css-tricks.com/css-modules-part-1-need/
https://magento.github.io/pwa-studio/technologies/basic-concepts/css-modules/

If you're looking for a hack, you could try adding something like `[class*="categoryTile"]` as a CSS selector to index.css.

Hope this helps :)

**Comment by markopredovic** [comment]
Ok thanks @rossmc . I just thought to have also global css for common styles, and for my cms pages and blocks loaded on pwa instance, currently pages and blocks missing styles. Also in Gatsby js you could have global css , beside module scope css, for example. That was idea
