### ISSUE TITLE
PWA Venia SEO : Meta Tags in Source HTML

### ISSUE THREAD

**Issue by Gameboy98** [rossmc/how-to-venia#5]
Hi Ross,
I hope this message finds you in good health and spirit, I am using venia to build a storefront. Still, for SEO Optimization, I cannot insert meta tags (title, description, keywords) into the source HTML. I have used serval methods like tweaking upward.yml and serving this via your method using server.js, But I'm unable to achieve this.
Attaching a screenshot for your reference

https://user-images.githubusercontent.com/34436284/198286253-87b3eb46-3974-4b75-b685-53fb0643624d.png

Please help me out.

**Comment by rossmc** [comment]
Hi @Gameboy98 I have not worked with this project of Magento PWA in about 3 years so I'm afraid I'm not best suited to answer this for you.

These docs were moved to the official Magento/Adobe docs, and have been updated since then. 
https://developer.adobe.com/commerce/pwa-studio/tutorials/setup-storefront/
